---
langs: 
  - :
  id : fr_FR 
  name : Francais 
  - :
  id : en_US 
  name : English
  - :
  id : ru_RU 
  name : Russe 
  - :
  id : de_DE 
  name : Allemand 
  - :
  id : es_ES 
  name : Espagnol 
  - :
  id : it_IT 
  name : Italien 
  - :
  id : id_ID 
  name : Indien
baseurl: "/"
home_bgfile: bg.jpg
sass:
  sass_dir: assets/css
  style: compressed
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
- jekyll-paginate
exclude:
- vendor
