---
langs: [fr_FR,en_US,de_DE,es_ES] 
baseurl: "/"
home_bgfile: bg.jpg
sass:
  sass_dir: assets/css
  style: compressed
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
- jekyll-paginate
exclude:
- vendor
